// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDt1xsuzY4hU6fyRG-JTHqlKr-yVnWLX8',
    appId: '1:1048829826767:web:5269e1052587939165c9ba',
    messagingSenderId: '1048829826767',
    projectId: 'quizgame-7f47d',
    authDomain: 'quizgame-7f47d.firebaseapp.com',
    storageBucket: 'quizgame-7f47d.firebasestorage.app',
    measurementId: 'G-9SVNB3N1SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzY6QeD6NuMeVpn6efwFPsDhuEkgc3Gco',
    appId: '1:1048829826767:android:88cf7052fdd1ff9b65c9ba',
    messagingSenderId: '1048829826767',
    projectId: 'quizgame-7f47d',
    storageBucket: 'quizgame-7f47d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB04nhD0EoTsy8xE_jQdhoG3osx2un1C9A',
    appId: '1:1048829826767:ios:bb08bc4bdfe6f2aa65c9ba',
    messagingSenderId: '1048829826767',
    projectId: 'quizgame-7f47d',
    storageBucket: 'quizgame-7f47d.firebasestorage.app',
    iosBundleId: 'com.example.quizGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB04nhD0EoTsy8xE_jQdhoG3osx2un1C9A',
    appId: '1:1048829826767:ios:bb08bc4bdfe6f2aa65c9ba',
    messagingSenderId: '1048829826767',
    projectId: 'quizgame-7f47d',
    storageBucket: 'quizgame-7f47d.firebasestorage.app',
    iosBundleId: 'com.example.quizGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDt1xsuzY4hU6fyRG-JTHqlKr-yVnWLX8',
    appId: '1:1048829826767:web:755e2db9a8e1603c65c9ba',
    messagingSenderId: '1048829826767',
    projectId: 'quizgame-7f47d',
    authDomain: 'quizgame-7f47d.firebaseapp.com',
    storageBucket: 'quizgame-7f47d.firebasestorage.app',
    measurementId: 'G-5F342TXTWH',
  );
}
